"""Email sender agent - sends research summary via Gmail MCP."""
import sys
import os
from datetime import datetime
from typing import Dict, Any
from langsmith import traceable

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mcp_tools.gmail_tool import GmailMCPTool


def format_email_body(topic: str, summary: str, key_findings: list, citations: list) -> str:
    """
    Format research summary as HTML email.
    
    Args:
        topic: Research topic
        summary: Research summary
        key_findings: List of key findings
        citations: List of citations
        
    Returns:
        HTML formatted email body
    """
    # Format key findings
    findings_html = "".join([
        f"<li>{finding}</li>"
        for finding in key_findings
    ])
    
    # Format citations
    citations_html = "".join([
        f'<li>{cite.get("claim", "N/A")} - <a href="{cite.get("source_url", "#")}">{cite.get("source_title", "Source")}</a></li>'
        for cite in citations
    ])
    
    html_body = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
        }}
        .summary {{
            background-color: #f8f9fa;
            padding: 20px;
            border-left: 4px solid #3498db;
            margin: 20px 0;
        }}
        .key-findings {{
            background-color: #e8f4f8;
            padding: 15px;
            border-radius: 5px;
        }}
        ul {{
            padding-left: 20px;
        }}
        li {{
            margin: 10px 0;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 0.9em;
            color: #666;
        }}
        a {{
            color: #3498db;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <h1>🔍 Research Summary: {topic}</h1>
    
    <div class="summary">
        <h2>Summary</h2>
        <p>{summary.replace(chr(10), '</p><p>')}</p>
    </div>
    
    <div class="key-findings">
        <h2>📌 Key Findings</h2>
        <ul>
            {findings_html}
        </ul>
    </div>
    
    <h2>📚 Citations</h2>
    <ul>
        {citations_html}
    </ul>
    
    <div class="footer">
        <p><em>This research summary was generated by MCP Research Agent on {datetime.now().strftime("%B %d, %Y at %I:%M %p")}</em></p>
        <p>Powered by Claude Sonnet 4, LangGraph, and Model Context Protocol</p>
    </div>
</body>
</html>
"""
    
    return html_body


@traceable(name="email_sender_agent", run_type="tool")
async def send_research_email(
    topic: str,
    client_email: str,
    summary: str,
    key_findings: list,
    citations: list
) -> Dict[str, Any]:
    """
    Send research summary via Gmail MCP.
    
    Args:
        topic: Research topic
        client_email: Recipient email address
        summary: Research summary
        key_findings: List of key findings
        citations: List of citations
        
    Returns:
        Dictionary with email_sent status and timestamp
    """
    gmail_tool = GmailMCPTool()
    
    # Format email
    subject = f"Research Summary: {topic}"
    body = format_email_body(topic, summary, key_findings, citations)
    
    # Send email
    try:
        result = await gmail_tool.send_email(
            to=client_email,
            subject=subject,
            body=body
        )
        
        return {
            "email_sent": True,
            "email_timestamp": datetime.now().isoformat(),
            "email_id": result.get("id", "unknown") if isinstance(result, dict) else "unknown"
        }
    except Exception as e:
        return {
            "email_sent": False,
            "email_timestamp": None,
            "error": str(e)
        }
